### ISSUE TITLE
Should option's label be placed around or after input?

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#49]
Currently, the options look like this:

```html
<li class="adg-combobox--available-options-list-item">
  <label>
    <input type="checkbox" name="hobbies[]" value="badminton">
    <span>Badminton</span>
  </label>
</li>
```

This makes it easy to make the whole `<li>` element clickable, incl. `hover` state, etc.:

```css
label:hover {
    cursor: pointer;
    background-color: rgb(255, 212, 212);
}
```

![CleanShot 2022-05-03 at 13 33 31@2x](https://user-images.githubusercontent.com/1814983/166445618-75634e8d-194e-4a39-816b-7edb95b0fc9e.png)

It also makes it easy to change the appearance of an option when it is checked:

```css
input:checked+span {
  font-weight: bold;
}
```

It also allows us to refrain from generating an `ID` for each option (which would otherwise be needed in a detached label's `for` attribute).

There was a request from Luis (ETH) though to place the `<input>` **left** to the `<label>` (instead of inside it). This would allow him to style the label depending on the input's value. But this would break the existing functionality, and it would not be easy to implement it in another (reasonable) way.
